In [1]:
!pip install us

Requirement already satisfied: us in /opt/anaconda3/lib/python3.12/site-packages (3.2.0)
Requirement already satisfied: jellyfish in /opt/anaconda3/lib/python3.12/site-packages (from us) (1.1.3)

In [2]:
import pandas as pd
import numpy as np
import us

In [3]:
# Read file and retrieve lendingclub dataset
raw_data = pd.read_csv("/Users/yeung/Desktop/Path Academic (AI in Finance)/Final Project/LendingClub.csv", header = 0, skiprows = 1, low_memory=False)
raw_data

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,10159548,NaN,15000.0,15000.0,15000.0,36 months,8.90%,476.30,A,A5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
1,10127816,NaN,24000.0,24000.0,24000.0,36 months,13.53%,814.80,B,B5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2,10139658,NaN,12000.0,12000.0,12000.0,36 months,13.53%,407.40,B,B5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
3,10129477,NaN,14000.0,14000.0,14000.0,36 months,12.85%,470.71,B,B4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
4,10119623,NaN,12000.0,12000.0,12000.0,36 months,11.99%,398.52,B,B3,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
188178,1059224,NaN,35000.0,35000.0,35000.0,36 months,15.96%,1229.81,C,C5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
188179,1058722,NaN,12000.0,12000.0,12000.0,36 months,16.29%,423.61,D,D1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
188180,1058291,NaN,12000.0,7775.0,7775.0,60 months,15.27%,186.08,C,C4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
188181,Total amount funded in policy code 1: 2700702175,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
188182,Total amount funded in policy code 2: 81866225,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
# Read file and retrieve GDP dataset
gdp = pd.read_csv("/Users/yeung/Desktop/Path Academic (AI in Finance)/Final Project/GDP.csv")
gdp

,GeoFIPS,GeoName,Region,TableName,LineCode,IndustryClassification,Description,Unit,1997,1998,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,"""00000""",United States *,,SAGDP2N,1.0,...,All industry total,Millions of current dollars,8577552.0,9062817.0,...,15542582.0,16197007.0,16784851.0,17527258.0,18238301.0,18745075.0,19542980.0,20611861.0,21433226.0,20936558.0
1,"""00000""",United States *,,SAGDP2N,2.0,...,Private industries,Millions of current dollars,7431992.0,7871500.0,...,13405520.0,14037519.0,14572341.0,15255889.0,15898859.0,16360179.0,17094245.0,18062184.0,18793750.0,18290860.0
2,"""00000""",United States *,,SAGDP2N,3.0,11,"Agriculture, forestry, fishing and hunting",Millions of current dollars,108637.0,99756.0,...,180945.0,179573.0,215601.0,201003.0,182283.0,166571.0,176625.0,178569.0,175373.0,175802.0
3,"""00000""",United States *,,SAGDP2N,4.0,111-112,Farms,Millions of current dollars,88136.0,79030.0,...,152249.0,148939.0,184621.0,168147.0,147384.0,130639.0,140053.0,140271.0,136080.0,(NA)
4,"""00000""",United States *,,SAGDP2N,5.0,113-115,"Forestry, fishing, and related activities",Millions of current dollars,20501.0,20726.0,...,28696.0,30634.0,30980.0,32856.0,34899.0,35932.0,36571.0,38298.0,39293.0,(NA)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5523,"""98000""",Far West,8,SAGDP2N,92.0,...,Private services-providing industries 3/,Millions of current dollars,985596.4,1064211.3,...,1976062.0,2075109.3,2181136.7,2313170.7,2486666.3,2618453.8,2789660.2,2954243.6,3138895.7,3104513.5
5524,Note: See the included footnote file.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5525,SAGDP2N: Gross domestic product (GDP) by state 1/,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5526,"Last updated: March 26, 2021-- new statistics ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5527,Source: U.S. Department of Commerce / Bureau o...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
# Keep loans issued during Q2 2012
lending_club_data = raw_data[raw_data['issue_d'].isin(['Apr-2012', 'May-2012', 'Jun-2012'])].copy()
lending_club_data

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
168732,1377559,NaN,2500.0,2500.0,2500.0,36 months,14.65%,86.24,C,C2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
168739,1377635,NaN,3000.0,3000.0,2750.0,36 months,7.90%,93.88,A,A4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
168769,1377314,NaN,5600.0,5600.0,5600.0,36 months,19.22%,205.90,D,D5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
168788,1327173,NaN,2800.0,2800.0,2800.0,36 months,7.62%,87.26,A,A3,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
168797,1363816,NaN,1925.0,1925.0,1925.0,36 months,10.74%,62.79,B,B2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180793,1190626,NaN,30000.0,30000.0,30000.0,36 months,10.74%,978.48,B,B2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
180923,1179389,NaN,33000.0,33000.0,33000.0,60 months,19.99%,874.12,E,E1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
180961,1185935,NaN,32000.0,32000.0,32000.0,36 months,17.99%,1156.72,D,D2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
180998,1164308,NaN,10000.0,10000.0,10000.0,36 months,13.11%,337.47,B,B4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
181062,1184439,NaN,35000.0,35000.0,35000.0,60 months,23.13%,989.29,F,F3,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
# Check and pick up what features/variables we are gonna use
lending_club_data.columns.tolist()

['id',
 'member_id',
 'loan_amnt',
 'funded_amnt',
 'funded_amnt_inv',
 'term',
 'int_rate',
 'installment',
 'grade',
 'sub_grade',
 'emp_title',
 'emp_length',
 'home_ownership',
 'annual_inc',
 'verification_status',
 'issue_d',
 'loan_status',
 'pymnt_plan',
 'url',
 'desc',
 'purpose',
 'title',
 'zip_code',
 'addr_state',
 'dti',
 'delinq_2yrs',
 'earliest_cr_line',
 'fico_range_low',
 'fico_range_high',
 'inq_last_6mths',
 'mths_since_last_delinq',
 'mths_since_last_record',
 'open_acc',
 'pub_rec',
 'revol_bal',
 'revol_util',
 'total_acc',
 'initial_list_status',
 'out_prncp',
 'out_prncp_inv',
 'total_pymnt',
 'total_pymnt_inv',
 'total_rec_prncp',
 'total_rec_int',
 'total_rec_late_fee',
 'recoveries',
 'collection_recovery_fee',
 'last_pymnt_d',
 'last_pymnt_amnt',
 'next_pymnt_d',
 'last_credit_pull_d',
 'last_fico_range_high',
 'last_fico_range_low',
 'collections_12_mths_ex_med',
 'mths_since_last_major_derog',
 'policy_code',
 'application_type',
 'annual_inc_joint',
 'dti_joint',
 'verification_status_joint',
 'acc_now_delinq',
 'tot_coll_amt',
 'tot_cur_bal',
 'open_acc_6m',
 'open_act_il',
 'open_il_12m',
 'open_il_24m',
 'mths_since_rcnt_il',
 'total_bal_il',
 'il_util',
 'open_rv_12m',
 'open_rv_24m',
 'max_bal_bc',
 'all_util',
 'total_rev_hi_lim',
 'inq_fi',
 'total_cu_tl',
 'inq_last_12m',
 'acc_open_past_24mths',
 'avg_cur_bal',
 'bc_open_to_buy',
 'bc_util',
 'chargeoff_within_12_mths',
 'delinq_amnt',
 'mo_sin_old_il_acct',
 'mo_sin_old_rev_tl_op',
 'mo_sin_rcnt_rev_tl_op',
 'mo_sin_rcnt_tl',
 'mort_acc',
 'mths_since_recent_bc',
 'mths_since_recent_bc_dlq',
 'mths_since_recent_inq',
 'mths_since_recent_revol_delinq',
 'num_accts_ever_120_pd',
 'num_actv_bc_tl',
 'num_actv_rev_tl',
 'num_bc_sats',
 'num_bc_tl',
 'num_il_tl',
 'num_op_rev_tl',
 'num_rev_accts',
 'num_rev_tl_bal_gt_0',
 'num_sats',
 'num_tl_120dpd_2m',
 'num_tl_30dpd',
 'num_tl_90g_dpd_24m',
 'num_tl_op_past_12m',
 'pct_tl_nvr_dlq',
 'percent_bc_gt_75',
 'pub_rec_bankruptcies',
 'tax_liens',
 'tot_hi_cred_lim',
 'total_bal_ex_mort',
 'total_bc_limit',
 'total_il_high_credit_limit',
 'revol_bal_joint',
 'sec_app_fico_range_low',
 'sec_app_fico_range_high',
 'sec_app_earliest_cr_line',
 'sec_app_inq_last_6mths',
 'sec_app_mort_acc',
 'sec_app_open_acc',
 'sec_app_revol_util',
 'sec_app_open_act_il',
 'sec_app_num_rev_accts',
 'sec_app_chargeoff_within_12_mths',
 'sec_app_collections_12_mths_ex_med',
 'sec_app_mths_since_last_major_derog',
 'hardship_flag',
 'hardship_type',
 'hardship_reason',
 'hardship_status',
 'deferral_term',
 'hardship_amount',
 'hardship_start_date',
 'hardship_end_date',
 'payment_plan_start_date',
 'hardship_length',
 'hardship_dpd',
 'hardship_loan_status',
 'orig_projected_additional_accrued_interest',
 'hardship_payoff_balance_amount',
 'hardship_last_payment_amount',
 'disbursement_method',
 'debt_settlement_flag',
 'debt_settlement_flag_date',
 'settlement_status',
 'settlement_date',
 'settlement_amount',
 'settlement_percentage',
 'settlement_term']

In [7]:
# Add a new column called 'fico' by averaging the FICO scores from raw dataset
lending_club_data['fico'] = (
    lending_club_data['fico_range_low'] + lending_club_data['fico_range_high']
) / 2

In [8]:
# Create binary default variable: Fully Paid = 0 (No default); Charged Off = 1 (Default)

lending_club_data = lending_club_data[
    lending_club_data['loan_status'].isin(['Fully Paid', 'Charged Off'])
].copy()

lending_club_data['default'] = lending_club_data['loan_status'].map({
    'Fully Paid': 0,
    'Charged Off': 1
})

lending_club_data[['loan_status','default']].head(10)
lending_club_data[['loan_status', 'default']].value_counts()

loan_status  default
Fully Paid   0          8668
Charged Off  1          1779
Name: count, dtype: int64

In [9]:
# Define the borrower and loan characteristics that will be considered in the analysis and modeling stages.
# Final feature selection will be applied after the GDP data are merged.

candidate_features = lending_club_data[[
    # Credit information
    'fico',
    'fico_range_low',
    'fico_range_high',
    'dti',
    'delinq_2yrs',
    'inq_last_6mths',
    'pub_rec',
    'revol_util',
    'total_acc',

    # Borrower information
    'annual_inc',
    'emp_length',
    'home_ownership',

    # Loan information
    'loan_amnt',
    'int_rate',
    'term',
    'grade',
    'purpose',

    # Location information (for GDP merge)
    'addr_state',
    'issue_d'
]]

candidate_features

,fico,fico_range_low,fico_range_high,dti,delinq_2yrs,inq_last_6mths,pub_rec,revol_util,total_acc,annual_inc,emp_length,home_ownership,loan_amnt,int_rate,term,grade,purpose,addr_state,issue_d
168732,662.0,660.0,664.0,17.00,0.0,0.0,0.0,54.6%,15.0,53000.0,10+ years,MORTGAGE,2500.0,14.65%,36 months,C,home_improvement,GA,Jun-2012
168739,732.0,730.0,734.0,8.21,0.0,0.0,0.0,26.1%,21.0,45600.0,10+ years,MORTGAGE,3000.0,7.90%,36 months,A,car,NV,Jun-2012
168769,662.0,660.0,664.0,17.30,0.0,0.0,0.0,91.5%,13.0,76320.0,6 years,RENT,5600.0,19.22%,36 months,D,debt_consolidation,FL,Jun-2012
168788,817.0,815.0,819.0,5.32,0.0,0.0,0.0,4.1%,6.0,65000.0,7 years,MORTGAGE,2800.0,7.62%,36 months,A,major_purchase,NY,Jun-2012
168797,702.0,700.0,704.0,4.23,0.0,2.0,0.0,21.3%,10.0,20700.0,< 1 year,OWN,1925.0,10.74%,36 months,B,home_improvement,AZ,Jun-2012
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180793,742.0,740.0,744.0,9.64,0.0,2.0,0.0,62.2%,16.0,175000.0,10+ years,MORTGAGE,30000.0,10.74%,36 months,B,small_business,TX,Apr-2012
180923,717.0,715.0,719.0,21.64,0.0,1.0,0.0,59%,40.0,90000.0,1 year,MORTGAGE,33000.0,19.99%,60 months,E,other,NC,Apr-2012
180961,712.0,710.0,714.0,24.49,0.0,2.0,0.0,55.3%,25.0,98000.0,10+ years,MORTGAGE,32000.0,17.99%,36 months,D,home_improvement,AZ,Apr-2012
180998,707.0,705.0,709.0,2.51,0.0,2.0,0.0,75.7%,13.0,80000.0,10+ years,RENT,10000.0,13.11%,36 months,B,credit_card,NJ,Apr-2012
181062,672.0,670.0,674.0,11.79,0.0,0.0,0.0,66.6%,22.0,132000.0,< 1 year,RENT,35000.0,23.13%,60 months,F,small_business,CA,Apr-2012

In [10]:
# Add a new column called 'issue_year' for later dataset merging
lending_club_data['issue_d'].head()

lending_club_data['issue_year'] = pd.to_datetime(
    lending_club_data['issue_d'],
    format='%b-%Y'
).dt.year

lending_club_data[['issue_d', 'issue_year']].head()

         issue_d  issue_year
168732  Jun-2012        2012
168739  Jun-2012        2012
168769  Jun-2012        2012
168788  Jun-2012        2012
168797  Jun-2012        2012

In [11]:
gdp.head()

,GeoFIPS,GeoName,Region,TableName,LineCode,IndustryClassification,Description,Unit,1997,1998,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,"""00000""",United States *,,SAGDP2N,1.0,...,All industry total,Millions of current dollars,8577552.0,9062817.0,...,15542582.0,16197007.0,16784851.0,17527258.0,18238301.0,18745075.0,19542980.0,20611861.0,21433226.0,20936558.0
1,"""00000""",United States *,,SAGDP2N,2.0,...,Private industries,Millions of current dollars,7431992.0,7871500.0,...,13405520.0,14037519.0,14572341.0,15255889.0,15898859.0,16360179.0,17094245.0,18062184.0,18793750.0,18290860.0
2,"""00000""",United States *,,SAGDP2N,3.0,11,"Agriculture, forestry, fishing and hunting",Millions of current dollars,108637.0,99756.0,...,180945.0,179573.0,215601.0,201003.0,182283.0,166571.0,176625.0,178569.0,175373.0,175802.0
3,"""00000""",United States *,,SAGDP2N,4.0,111-112,Farms,Millions of current dollars,88136.0,79030.0,...,152249.0,148939.0,184621.0,168147.0,147384.0,130639.0,140053.0,140271.0,136080.0,(NA)
4,"""00000""",United States *,,SAGDP2N,5.0,113-115,"Forestry, fishing, and related activities",Millions of current dollars,20501.0,20726.0,...,28696.0,30634.0,30980.0,32856.0,34899.0,35932.0,36571.0,38298.0,39293.0,(NA)

In [12]:
# Check dataset and pick up what features/variables we are gonna use
gdp.columns.tolist()

['GeoFIPS',
 'GeoName',
 'Region',
 'TableName',
 'LineCode',
 'IndustryClassification',
 'Description',
 'Unit',
 '1997',
 '1998',
 '1999',
 '2000',
 '2001',
 '2002',
 '2003',
 '2004',
 '2005',
 '2006',
 '2007',
 '2008',
 '2009',
 '2010',
 '2011',
 '2012',
 '2013',
 '2014',
 '2015',
 '2016',
 '2017',
 '2018',
 '2019',
 '2020']

In [13]:
# The dataset contains GDP information by different industries, so we only select "All industry total" to represent overall economic activity.
gdp = gdp[
    gdp['Description'] == 'All industry total'
].copy()

gdp.head()

,GeoFIPS,GeoName,Region,TableName,LineCode,IndustryClassification,Description,Unit,1997,1998,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,"""00000""",United States *,,SAGDP2N,1.0,...,All industry total,Millions of current dollars,8577552.0,9062817.0,...,15542582.0,16197007.0,16784851.0,17527258.0,18238301.0,18745075.0,19542980.0,20611861.0,21433226.0,20936558.0
96,"""01000""",Alabama,5,SAGDP2N,1.0,...,All industry total,Millions of current dollars,104716.9,110181.3,...,181929.9,186553.9,192166.5,195037.7,200197.5,204454.7,210895.7,221030.7,228142.6,224870.6
188,"""02000""",Alaska,8,SAGDP2N,1.0,...,All industry total,Millions of current dollars,25800.0,24227.6,...,56333.9,57717.5,56625.3,55750.6,50728.1,49755.6,51737.0,54292.9,54385.6,50246.7
280,"""04000""",Arizona,6,SAGDP2N,1.0,...,All industry total,Millions of current dollars,132290.9,143286.2,...,257881.1,268068.2,275007.5,284851.4,298615.0,313056.5,330146.6,350718.3,370119.1,372461.0
372,"""05000""",Arkansas,5,SAGDP2N,1.0,...,All industry total,Millions of current dollars,59826.9,62397.8,...,105107.8,107718.8,112764.6,116151.8,117734.3,119191.8,122978.5,127761.3,130954.1,129073.9

In [14]:
# Select the state name and the 2012 GDP value because the LendingClub sample is restricted to loans issued during Q2 2012.
# The GDP measure represents Total state GDP rather than GDP per capita.
# The values are reported in millions of current dollars.
gdp_2012 = gdp[
    ['GeoName', '2012']
].copy()

In [15]:
# Rename the GDP column to indicate that it represents state GDP in 2012.
gdp_2012 = gdp_2012.rename(
    columns={'2012':'state_gdp_2012'}
)

gdp_2012.head()

             GeoName state_gdp_2012
0    United States *     16197007.0
96           Alabama       186553.9
188           Alaska        57717.5
280          Arizona       268068.2
372         Arkansas       107718.8

In [16]:
# Convert full state names in the GDP dataset into two-letter state abbreviations so that they match LendingClub's "addr_state" variable. 

# Example:
# California -> CA
# Massachusetts -> MA
# New York -> NY

def get_state_abbr(state_name):
    
    # Handle the District of Columbia explicitly.
    # BEA reports it as "District of Columbia", while LendingClub identifies borrowers from Washington, DC using "DC"
    if state_name == 'District of Columbia':
        return 'DC'
    
    # Use the "us" package to convert the remaining state names into their standard two-letter abbreviations
    state = us.states.lookup(state_name)
    
    if state:
        return state.abbr
    
    # Return None for observations that are not individual states, such as regional or national aggregates
    return None


# Apply the state-name conversion to the GDP dataset
gdp_2012['addr_state'] = gdp_2012['GeoName'].apply(
    get_state_abbr
)

# Check any geographic observations that could not be mapped
# These should only be non-state geographic aggregates
gdp_2012[
    gdp_2012['addr_state'].isna()
][['GeoName']]

              GeoName
0     United States *
4788      New England
4880          Mideast
4972      Great Lakes
5064           Plains
5156        Southeast
5248        Southwest
5340   Rocky Mountain
5432         Far West

In [17]:
# Remove geographic observations that are not individual states or DC.
# These rows cannot be matched to LendingClub borrowers because borrowers
# are identified using state abbreviations.
gdp_2012 = gdp_2012.dropna(
    subset=['addr_state']
).copy()

# Keep only the variables needed for the LendingClub merge.
gdp_2012 = gdp_2012[
    ['addr_state', 'state_gdp_2012']
]

# Check the cleaned state-level GDP dataset.
gdp_2012.head()

    addr_state state_gdp_2012
96          AL       186553.9
188         AK        57717.5
280         AZ       268068.2
372         AR       107718.8
464         CA      2144089.6

In [18]:
# Confirm the number of state-level GDP observations
# Ideally, this should represent the 50 states plus Washington, DC
print("Number of state/DC GDP observations:", len(gdp_2012))

# Check for duplicate state abbreviations
print(
    "Duplicate state abbreviations:",
    gdp_2012['addr_state'].duplicated().sum()
)

Number of state/DC GDP observations: 51
Duplicate state abbreviations: 0

In [19]:
# Merge 2012 state GDP into the LendingClub dataset using the borrower's state of residence ("addr_state") as the matching key
# A LEFT JOIN is used so that all LendingClub loans are retained, even if a GDP match is temporarily missing
merged_data = lending_club_data.merge(
    gdp_2012,
    on='addr_state',
    how='left'
)

# Preview the merged data.
merged_data.head()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term,fico,default,issue_year,state_gdp_2012
0,1377559,NaN,2500.0,2500.0,2500.0,36 months,14.65%,86.24,C,C2,...,NaN,NaN,NaN,NaN,NaN,NaN,662.0,0,2012,443566.1
1,1377635,NaN,3000.0,3000.0,2750.0,36 months,7.90%,93.88,A,A4,...,NaN,NaN,NaN,NaN,NaN,NaN,732.0,0,2012,127789.1
2,1377314,NaN,5600.0,5600.0,5600.0,36 months,19.22%,205.90,D,D5,...,NaN,NaN,NaN,NaN,NaN,NaN,662.0,0,2012,768722.9
3,1327173,NaN,2800.0,2800.0,2800.0,36 months,7.62%,87.26,A,A3,...,NaN,NaN,NaN,NaN,NaN,NaN,817.0,0,2012,1323400.8
4,1363816,NaN,1925.0,1925.0,1925.0,36 months,10.74%,62.79,B,B2,...,NaN,NaN,NaN,NaN,NaN,NaN,702.0,0,2012,268068.2

In [20]:
# Validate the GDP merge by comparing the number of loans before and after merging
# A successful left join should preserve the same number of LendingClub observations
print("Loans before GDP merge:", len(lending_club_data))
print("Loans after GDP merge:", len(merged_data))

# Count loans that did not receive a GDP value
print(
    "Loans with missing GDP:",
    merged_data['state_gdp_2012'].isna().sum()
)

Loans before GDP merge: 10447
Loans after GDP merge: 10447
Loans with missing GDP: 0

In [21]:
# Identify which borrower states, if any, failed to match with the state GDP dataset
# This allows us to fix mapping problems instead of simply deleting unmatched observations
unmatched_states = (
    merged_data.loc[
        merged_data['state_gdp_2012'].isna(),
        'addr_state'
    ]
    .value_counts()
)

unmatched_states

Series([], Name: count, dtype: int64)

In [22]:
merged_data

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term,fico,default,issue_year,state_gdp_2012
0,1377559,NaN,2500.0,2500.0,2500.0,36 months,14.65%,86.24,C,C2,...,NaN,NaN,NaN,NaN,NaN,NaN,662.0,0,2012,443566.1
1,1377635,NaN,3000.0,3000.0,2750.0,36 months,7.90%,93.88,A,A4,...,NaN,NaN,NaN,NaN,NaN,NaN,732.0,0,2012,127789.1
2,1377314,NaN,5600.0,5600.0,5600.0,36 months,19.22%,205.90,D,D5,...,NaN,NaN,NaN,NaN,NaN,NaN,662.0,0,2012,768722.9
3,1327173,NaN,2800.0,2800.0,2800.0,36 months,7.62%,87.26,A,A3,...,NaN,NaN,NaN,NaN,NaN,NaN,817.0,0,2012,1323400.8
4,1363816,NaN,1925.0,1925.0,1925.0,36 months,10.74%,62.79,B,B2,...,NaN,NaN,NaN,NaN,NaN,NaN,702.0,0,2012,268068.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10442,1190626,NaN,30000.0,30000.0,30000.0,36 months,10.74%,978.48,B,B2,...,NaN,NaN,NaN,NaN,NaN,NaN,742.0,0,2012,1410447.8
10443,1179389,NaN,33000.0,33000.0,33000.0,60 months,19.99%,874.12,E,E1,...,NaN,NaN,NaN,NaN,NaN,NaN,717.0,1,2012,439539.7
10444,1185935,NaN,32000.0,32000.0,32000.0,36 months,17.99%,1156.72,D,D2,...,NaN,NaN,NaN,NaN,NaN,NaN,712.0,0,2012,268068.2
10445,1164308,NaN,10000.0,10000.0,10000.0,36 months,13.11%,337.47,B,B4,...,NaN,NaN,NaN,NaN,NaN,NaN,707.0,0,2012,519569.0
10446,1184439,NaN,35000.0,35000.0,35000.0,60 months,23.13%,989.29,F,F3,...,NaN,NaN,NaN,NaN,NaN,NaN,672.0,1,2012,2144089.6

In [23]:
# Save merged_data into csv file
merged_data.to_csv(
    "merged_data.csv",
    index=False
)

In [24]:
# Select the final variables used for EDA, statistical analysis, and machine learning modeling. addr_state is retained for geographic analysis and validation, but will not be used as a predictor in the baseline-vs-GDP models.

final_data = merged_data[
[
    # Credit
    'fico',
    'dti',
    'delinq_2yrs',
    'inq_last_6mths',
    'pub_rec',
    'revol_util',
    'total_acc',

    # Borrower
    'annual_inc',
    'emp_length',
    'home_ownership',

    # Loan
    'loan_amnt',
    'int_rate',
    'term',
    'grade',
    'purpose',

    # Economic indicator
    'addr_state',
    'state_gdp_2012',

    # Target
    'default'
]
]

In [25]:
# Final Dataset Validation

# Check the dimensions of the final modeling dataset.
print("Final dataset shape:", final_data.shape)

# Check missing values in each selected variable.
print("\nMissing values:")
print(
    final_data.isna()
    .sum()
    .sort_values(ascending=False)
)

# Check for duplicated observations.
print(
    "\nDuplicate rows:",
    final_data.duplicated().sum()
)

# Confirm the binary target distribution.
# 0 = Fully Paid
# 1 = Charged Off
print("\nDefault distribution:")
print(final_data['default'].value_counts())

print("\nDefault rate:")
print(final_data['default'].value_counts(normalize=True))

# Confirm that every borrower has matched GDP information.
print(
    "\nMissing GDP values:",
    final_data['state_gdp_2012'].isna().sum()
)

# Check how many borrower states are represented.
print(
    "\nNumber of borrower states:",
    final_data['addr_state'].nunique()
)

Final dataset shape: (10447, 18)

Missing values:
emp_length        347
revol_util          9
fico                0
loan_amnt           0
state_gdp_2012      0
addr_state          0
purpose             0
grade               0
term                0
int_rate            0
home_ownership      0
dti                 0
annual_inc          0
total_acc           0
pub_rec             0
inq_last_6mths      0
delinq_2yrs         0
default             0
dtype: int64

Duplicate rows: 0

Default distribution:
default
0    8668
1    1779
Name: count, dtype: int64

Default rate:
default
0    0.829712
1    0.170288
Name: proportion, dtype: float64

Missing GDP values: 0

Number of borrower states: 43

In [26]:
# Missing values in emp_length (347) and revol_util (9) are retained and will be handled during model preprocessing.

In [27]:
final_data

,fico,dti,delinq_2yrs,inq_last_6mths,pub_rec,revol_util,total_acc,annual_inc,emp_length,home_ownership,loan_amnt,int_rate,term,grade,purpose,addr_state,state_gdp_2012,default
0,662.0,17.00,0.0,0.0,0.0,54.6%,15.0,53000.0,10+ years,MORTGAGE,2500.0,14.65%,36 months,C,home_improvement,GA,443566.1,0
1,732.0,8.21,0.0,0.0,0.0,26.1%,21.0,45600.0,10+ years,MORTGAGE,3000.0,7.90%,36 months,A,car,NV,127789.1,0
2,662.0,17.30,0.0,0.0,0.0,91.5%,13.0,76320.0,6 years,RENT,5600.0,19.22%,36 months,D,debt_consolidation,FL,768722.9,0
3,817.0,5.32,0.0,0.0,0.0,4.1%,6.0,65000.0,7 years,MORTGAGE,2800.0,7.62%,36 months,A,major_purchase,NY,1323400.8,0
4,702.0,4.23,0.0,2.0,0.0,21.3%,10.0,20700.0,< 1 year,OWN,1925.0,10.74%,36 months,B,home_improvement,AZ,268068.2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10442,742.0,9.64,0.0,2.0,0.0,62.2%,16.0,175000.0,10+ years,MORTGAGE,30000.0,10.74%,36 months,B,small_business,TX,1410447.8,0
10443,717.0,21.64,0.0,1.0,0.0,59%,40.0,90000.0,1 year,MORTGAGE,33000.0,19.99%,60 months,E,other,NC,439539.7,1
10444,712.0,24.49,0.0,2.0,0.0,55.3%,25.0,98000.0,10+ years,MORTGAGE,32000.0,17.99%,36 months,D,home_improvement,AZ,268068.2,0
10445,707.0,2.51,0.0,2.0,0.0,75.7%,13.0,80000.0,10+ years,RENT,10000.0,13.11%,36 months,B,credit_card,NJ,519569.0,0
10446,672.0,11.79,0.0,0.0,0.0,66.6%,22.0,132000.0,< 1 year,RENT,35000.0,23.13%,60 months,F,small_business,CA,2144089.6,1

In [28]:
final_data.to_csv(
    "LendingClub_GDP_Final.csv",
    index=False
)